
[global]
address = "0.0.0.0"
port = 8080

[debug]
base-URI = "http://localhost:8080"
from = "noreply@localhost"
x-accel-redirect = false
token_secret = "hagrid"
token_validity = 3600
template_dir = "dist/templates"
assets_dir = "dist/assets"
keys_internal_dir = "state/keys-internal"
keys_external_dir = "state/keys-external"
token_dir = "state/tokens"
tmp_dir = "state/tmp"
mail_rate_limit = 60
maintenance_file = "state/maintenance"
enable_prometheus = false
email_template_dir = "dist/email-templates"

[staging]
base-URI = "http://localhost:8080"
# base-URI-Onion = "http://localhost:8080"
from = "noreply@localhost"
x-accel-redirect = false
token_secret = "hagrid"
token_validity = 3600
# NOTE: there is an index in my templates file index.html.mbs
template_dir = "templates"
assets_dir = "public/assets"
keys_internal_dir = "keys"
keys_external_dir = "public/keys"
token_dir = "tokens"
tmp_dir = "tmp"
mail_rate_limit = 3600
maintenance_file = "maintenance"
enable_prometheus = false
email_template_dir = "email-templates"

[release]
base-URI = "http://localhost:8080"
# base-URI-Onion = "http://localhost:8080"
from = "noreply@localhost"
x-accel-redirect = false
token_secret = "hagrid"
token_validity = 3600
# NOTE: there is an index in my templates file index.html.mbs
template_dir = "templates"
assets_dir = "public/assets"
keys_internal_dir = "keys"
keys_external_dir = "public/keys"
token_dir = "tokens"
tmp_dir = "tmp"
mail_rate_limit = 3600
maintenance_file = "maintenance"
enable_prometheus = false
email_template_dir = "email-templates"
